name: Tag n Slack
description: Creates a new Tag from `CHANGELOG.md` using the `version` from `package.json` and notifies Slack about the release.
inputs:
    github-access-token:
        description: Access token for github allowed to read existing Tags of a repository
        required: true
    slack-webhook-url:
        description: Provide the Slack Webhook URL
        required: true
    slack-release-link:
        description: Url of the "Visit" button in the Slack message
        required: true
    package-json-path:
        description: Path of package.json
        default: './'
    slack-icon-emoji:
        description: Emoji used in the Slack message (default = :rocket:)
        default: ':rocket:'
    project-name:
        description: Name of the project (default = Github Repository Name)
        default: ${{ github.event.repository.name }}
    version-increment-strategy:
        description: Version management strategy, either changelog-file or github-releases
        default: 'changelog-file'
    target-commitish:
        description: Main branch used by github-releases
        default: 'main'
    project-owner:
        description: the repo owner's handle
        default: ${{ github.event.repository.owner.login }}
    remove-images:
        description: Remove images and github user attachments from the Slack message
        default: ${{ github.event.repository.private }}
    ticket-config:
        description: JSON string to format the ticketing system links
        default: '{}'
outputs:
    release:
        description: The Github release object
runs:
    using: node20
    main: action/index.js
