  name: Tag n Slack
  description: Creates a new Tag with a Changelog from `CHANGELOG.md` using the `version` from `package.json` and notifies Slack about the release.
  inputs:
    github-access-token:
      description: Access token for github allowed to read existing Tags of a repository
      required: true
    slack-webhook-url:
      description: Provide the Slack Webhook URL
      required: true
    package-json-path:
      description: Path of package.json
      default: './'
    slack-icon:
      description: Slack Icon URL
      default: 'https://emoji.slack-edge.com/T02SEBT8V/perspective-power2/5faf2f1dd7e6fe60.png'
    slack-color:
        description: Slack message highlight color
        default: 'good'
    slack-username:
      description: Slack username
      default: 'Release Tracker'
  runs:
    using: node16
    main: action/index.js
